spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
        url: jdbc:mysql://localhost:3306/MovieDataBase
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver

  server:
      port: 8091